<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Budget'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/css/extjs/statusbar.css')
						->prependStylesheet($this->basePath() . '/css/extjs/notification.css')
//                        ->prependStylesheet($this->basePath() . '/css/extjs/ext-theme-access/ext-theme-access-all.css')
                        ->prependStylesheet($this->basePath() . '/css/extjs/ext-theme-gray/ext-theme-gray-all.css')
//                        ->prependStylesheet($this->basePath() . '/css/extjs/ext-theme-classic/ext-theme-classic-all.css')
//                        ->prependStylesheet($this->basePath() . '/css/extjs/ext-theme-neptune/ext-theme-neptune-all.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
//                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                      ->prependFile($this->basePath() . '/app/app.js')
                                      ->prependFile($this->basePath() . '/js/extjs/locale/ext-lang-sr.js')
                                      ->prependFile($this->basePath() . '/js/extjs/ext-all-debug-w-comments.js')
//									  ->prependFile($this->basePath() . '/js/extjs/ext-all.js') ?>
		
    </head>
    <body>
		<div id="loading"><span class="title" style="display: none;">Budget is loading</span><span class="logo"></span></div>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
